# Generated by Django 6.0 on 2025-12-25 14:44

import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/')),
                ('pin', models.CharField(default=docs.models.gen_pin, editable=False, max_length=6)),
                ('qr', models.ImageField(blank=True, upload_to='qr/')),
                ('pdf_image', models.ImageField(blank=True, upload_to='pdf_preview/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document_code', models.CharField(blank=True, max_length=10)),
                ('ducument_son', models.IntegerField(blank=True, null=True)),
                ('ariza_berilgan', models.DateField(blank=True, null=True)),
                ('bergan_tashkilot', models.CharField(blank=True, max_length=1024, null=True)),
                ('imzolagan', models.CharField(blank=True, max_length=512, null=True)),
                ('ijrochi', models.CharField(blank=True, max_length=512, null=True)),
                ('eri_bergan', models.CharField(blank=True, max_length=512, null=True)),
                ('eri_amal_qilish_b', models.DateField(blank=True, null=True)),
                ('eri_tugash', models.DateField(blank=True, null=True)),
                ('imzolagan_h', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
