# Generated by Django 6.0 on 2025-12-22 13:31

import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/')),
                ('pin', models.CharField(default=docs.models.gen_pin, editable=False, max_length=6)),
                ('qr', models.ImageField(blank=True, upload_to='qr/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
