# Generated by Django 6.0 on 2025-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_image',
            field=models.ImageField(blank=True, upload_to='pdf_preview/'),
        ),
    ]
