# Generated by Django 6.0 on 2025-12-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_pdf_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf_image',
            new_name='pdf_preview',
        ),
    ]
