# Generated by Django 6.0 on 2025-12-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_rename_pdf_image_document_pdf_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf_preview',
            new_name='pdf_image',
        ),
    ]
